### PR TITLE
Execute pipeline locally

### PR DESCRIPTION
**Pull request by c0d1ngm0nk3y**
Based on #11

### CODE REVIEW

**Comment by c0d1ngm0nk3y** [comment]
The diff should become clearer once #11 is merged.

**Review by Haegi — APPROVED** [review]
LGTM

**Comment by Haegi** [comment]
Running the pipeline (locally) in a docker container would make it maybe a little bit easier :)

**Comment by c0d1ngm0nk3y** [comment]
I will wait for #11 since this is based on top.

**Pull request merged**
